// pobranie wszystkich tagów bez konwersji na obiekty
GET http://localhost:3000/api/tags/raw

###
GET http://localhost:3000/api/tags
// pobranie wszystkich tagów z konwersją na obiekty
###
GET http://localhost:3000/api/tags/1
# pobranie jednego taga
###
POST http://localhost:3000/api/tags
 // utworzenie nowego taga

 {
    "name": "tag",
    "popularity": 100
 }
###
PATCH http://localhost:3000/api/photos/tags HTTP/1.1
content-type: application/json

{
    "photoId": 0,
    "tagName": "#love"
}
  // aktualizacja danych zdjęcia o nowy tag


    
###
PATCH http://localhost:3000/api/photos/tags/mass HTTP/1.1
 // aktualizacja danych zdjęcia o tablicę nowych tag-ów
 content-type: application/json

{
    "photoId": 0,
    "tagName": ["#love", "#tag"]
}

###
GET http://localhost:3000/api/photos/tags/0
 // pobranie tagów danego zdjęcia